package driver

import (
	"os"
	"path/filepath"
	"sort"
	"strings"

	"kigumi/internal/syntax"
	"kigumi/internal/token"
)

// Package is one directory of .kg files. Path is the canonical import path
// relative to the module root ("repostat/parse"); std packages carry the
// "std/" prefix.
type Package struct {
	Path  string
	Dir   string
	Files []*syntax.Tree
	// Std marks declaration stubs: bodiless functions are allowed there.
	Std bool
	// Header marks a package generated by a Header import
	// like Std it stays in an
	// explicit entry's diagnostic scope even when unimported, so a skipped
	// declaration can't go silently unreported.
	Header bool
	// Module is the dependency the package came from; "" for the module
	// being built.
	Module string
}

// Module is a module root plus the std stubs it can import.
type Module struct {
	Root string
	// Name is the module name from mod.kg; it prefixes the import paths of
	// the module's own packages. "" for a manifest-less directory.
	Name  string
	Entry string
	// ExplicitEntry marks that the caller picked one root (an entry file,
	// or a cmd/* package dir) rather than the whole module; it narrows
	// checking to that entry's build scope (check.go's buildScope).
	ExplicitEntry bool
	overlay       map[string][]byte
	// diagsReported marks that reportDiagnostics already wrote m's
	// diagnostics once (diag_severity.go); a build's later compile() call
	// then skips the write shared.Load already made.
	diagsReported bool
	// FileStore numbers every parsed source so diagnostics can point
	// across files.
	FileStore *token.SourceStore
	stats     Stats
	Packages  map[string]*Package
	// Order lists package paths sorted for deterministic iteration.
	Order []string
	// Links and Sources collect the C libraries and sources of the module
	// and its dependencies, search paths and sources made absolute.
	Links   []Link
	Sources []string
	// Manifest is mod.kg, or the leading records of the script.
	Manifest ModFile
	// Selected is what minimal version selection chose for each dependency.
	Selected map[string]Require
	// ScriptFile is the root-relative entry that carried the manifest.
	ScriptFile string
	local      Local
	target     Target
	// deny, ceiling and artifactName carry an artifact's declared
	// availability (LoadOptions) through to semModule (check.go).
	deny         []string
	ceiling      string
	artifactName string
}

// LoadOptions controls which files become part of the module.
type LoadOptions struct {
	// Test includes name_test.kg files.
	Test bool
	// StdRoot is the std directory itself (its subdirectories become the
	// std/... packages); empty skips std.
	StdRoot string
	// Entry names the entry file (root-relative); empty selects the script
	// file of a package under cmd/.
	Entry string
	// NoDeps leaves required modules out (manifest tooling that must work
	// before `kigumi get`).
	NoDeps bool
	// Target selects platform-suffixed files; the zero value is the host.
	Target Target
	// NoLocal ignores mod.local.kg, so a build sees the same versions the
	// module's users get.
	NoLocal bool
	// Overlay maps absolute paths to contents that replace the files on disk
	// (editor buffers); paths that do not exist on disk are added.
	Overlay map[string][]byte
	// Deny and Ceiling are an artifact's declared availability
	// (Artifact.availability): Deny bars
	// exact std import paths, Ceiling caps std packages by layer short
	// name ("core"/"alloc"/"sys"/"tool", "" for no ceiling). ArtifactName
	// names the declaring artifact for the diagnostic.
	Deny         []string
	Ceiling      string
	ArtifactName string
}

// LoadModule parses every package under root and, when configured, the std
// stubs. Parse diagnostics stay on each Tree; loading itself only fails on I/O.
func LoadModule(root string, opts LoadOptions) (*Module, error) {
	m := &Module{Root: root, Entry: opts.Entry, ExplicitEntry: opts.Entry != "", overlay: opts.Overlay, Packages: map[string]*Package{}, local: Local{Replaces: map[string]string{}}, target: opts.Target, deny: opts.Deny, ceiling: opts.Ceiling, artifactName: opts.ArtifactName}
	if m.target.OS == "" {
		m.target = HostTarget()
	}
	mf, hasMod, err := ReadModFile(root)
	if err != nil {
		return nil, err
	}
	m.Name, m.Manifest = mf.Name, mf
	skip := func(dir string) bool { return skipDir(dir, opts.StdRoot) || IsModuleRoot(dir) }
	if err := m.loadTree(root, m.Name, false, opts.Test, skip); err != nil {
		return nil, err
	}
	if err := m.scriptManifest(hasMod); err != nil {
		return nil, err
	}
	if err := m.addNative(root, m.Manifest); err != nil {
		return nil, err
	}
	if err := m.addHeaders(root, m.Manifest); err != nil {
		return nil, err
	}
	if !opts.NoLocal {
		if m.local, err = ReadLocal(root); err != nil {
			return nil, err
		}
	}
	if !opts.NoDeps {
		lock, err := ReadLock(root)
		if err != nil {
			return nil, err
		}
		enforceLock := true
		if m.ScriptFile != "" {
			scriptLock := filepath.Join(root, filepath.FromSlash(m.ScriptFile)) + ".lock.kg"
			if _, statErr := os.Stat(scriptLock); statErr != nil {
				enforceLock = false
			} else if lock, err = ReadLockFile(scriptLock); err != nil {
				return nil, err
			}
		}
		if err := m.loadDeps(opts, lock, enforceLock); err != nil {
			return nil, err
		}
	}
	if opts.StdRoot != "" {
		if err := m.loadTree(opts.StdRoot, "std", true, false, nil); err != nil {
			return nil, err
		}
	}
	m.Order = make([]string, 0, len(m.Packages))
	for p := range m.Packages {
		m.Order = append(m.Order, p)
	}
	sort.Strings(m.Order)
	return m, nil
}

// Rel strips the module name from one of its own package paths, giving the
// directory relative to the root ("cmd/app"); other paths pass through.
func (m *Module) Rel(pkgPath string) string {
	if m.Name == "" {
		return pkgPath
	}
	if pkgPath == m.Name {
		return ""
	}
	return strings.TrimPrefix(pkgPath, m.Name+"/")
}
