package sem

// Diagnostic catalog, 4xx inference/literals/lambdas, 5xx calls/overloads/
// methods, 6xx operators/index/pipeline/fallback, 7xx control flow and
// statements.
var (
	cTypeMismatch        = defineCode("E400", "type-mismatch", "expected `{expected}`, found `{actual}`")
	cBranchTypeMismatch  = defineCode("E401", "branch-type-mismatch", "branches have different types: `{a}` and `{b}`")
	cLiteralOutOfRange   = defineCode("E402", "literal-out-of-range", "`{lit}` does not fit `{type}`")
	cLiteralFloatIntoInt = defineCode("E403", "literal-float-into-int", "float literal `{lit}` cannot be `{type}`")
	cResultAlready       = defineCode("E404", "result-already", "`{type}` is already a `Result`; write `Ok(...)` or `Err(...)` explicitly")
	cNumericMixed        = defineCode("E405", "numeric-mixed", "`{a}` and `{b}` cannot be mixed; convert explicitly")
	cCharInvalid         = defineCode("E406", "char-invalid", "invalid character literal")
	cInterpolationType   = defineCode("E407", "interpolation-type", "cannot interpolate `{type}`; call `.display()`")
	cShellInterpType     = defineCode("E408", "shell-interp-type", "`{type}` cannot be a shell argument")
	cLambdaArity         = defineCode("E409", "lambda-arity", "lambda takes {n} parameter{s}, `{type}` expects {m}")
	cLambdaParamAnnot    = defineCode("E410", "lambda-param-annotation", "parameter `{name}` needs a type annotation")
	cLambdaParamMismatch = defineCode("E411", "lambda-param-mismatch", "parameter `{name}` is `{a}`, expected `{b}`")
	cClosureCapturesRef  = defineCode("E412", "closure-captures-borrow", "closure cannot capture the borrow `{name}`")
	cClosureNotPlainFn   = defineCode("E413", "closure-not-plain-fn", "closure captures `{name}` ({why}) and cannot be a plain `fn`; use `F: Fn[...]`")
	cIfValueNeedsElse    = defineCode("E414", "if-value-needs-else", "`if` in value position needs `else`")
	cConditionNotBool    = defineCode("E415", "condition-not-bool", "condition must be `Bool`, found `{type}`")
	cMethodValueMoveOnly = defineCode("E416", "method-value-move-only", "cannot form a method value on move-only `{type}`; write a lambda")
	cVariadicNoValue     = defineCode("E418", "variadic-no-value", "variadic function `{name}` has no function value; write `(a) => {name}(..., ...a)`")
	cIntrinsicNotValue   = defineCode("E419", "intrinsic-not-value", "`{name}` is a compiler intrinsic, not a value")
	cOverloadValueAmbig  = defineCode("E420", "overload-value-ambiguous", "`{name}` is overloaded; annotate the function type")
	cFnValueEffects      = defineCode("E421", "fn-value-effects", "`{actual}` cannot be used as `{expected}`: it is not declared `{mod}`")
	cClosureContract     = defineCode("E422", "closure-contract", "closure is not `{mod}` ({why})")
	cFnItemContract      = defineCode("E423", "fn-item-contract", "`{name}` is not `{mod}` ({why})")
	cVariantCtorValue    = defineCode("E424", "variant-ctor-value", "`{name}` needs a payload; write `(x) => {name}(x)`")
	cErrorNotConform     = defineCode("E425", "error-not-conform", "`{type}` does not conform to `Error` (no `fn message(self) -> String`)")

	cNotCallable         = defineCode("E500", "not-callable", "`{type}` is not callable")
	cCallArity           = defineCode("E501", "call-arity", "`{name}` expects {n} argument{s}, {m} given")
	cOverloadNoMatch     = defineCode("E502", "overload-no-match", "no overload of `{name}` takes ({types}); candidates: {list}")
	cOverloadAmbiguous   = defineCode("E503", "overload-ambiguous", "call to `{name}` is ambiguous: {list}; annotate the arguments")
	cOverloadLambdaAnnot = defineCode("E504", "overload-lambda-annotate", "annotate the lambda parameters: `{name}` is overloaded")
	cVariadicMixed       = defineCode("E505", "variadic-mixed", "cannot mix listed arguments with `...expr`")
	cSpreadNonVariadic   = defineCode("E506", "spread-non-variadic", "`{name}` is not variadic")
	cSpreadType          = defineCode("E507", "spread-type", "`...{e}` must be `Array[{T}]`, found `{type}`")
	cOrPatternBinding    = defineCode("E509", "or-pattern-binding", "`{name}` binds a name inside `|` alternatives; alternatives may only test")
	cVariantNoPayload    = defineCode("E508", "variant-no-payload", "`{name}` has no payload; write `{name}` without parentheses")
	cVariantArity        = defineCode("E522", "variant-arity", "`{name}` takes {n} payload value{s}, {m} given")
	cMemberNotFound      = defineCode("E510", "member-not-found", "`{type}` has no field or method `{name}`")
	cMethodNeedsCall     = defineCode("E511", "method-needs-call", "`{name}` is a method; call it: `{name}()`")
	cAssocIsMethod       = defineCode("E512", "assoc-is-method", "`{name}` is a method; call it on a value: `v.{name}()`")
	cFieldOnType         = defineCode("E513", "field-on-type", "`{name}` is a field; access it on a value")
	cMethodAsAssoc       = defineCode("E514", "method-as-assoc", "`{name}` is an associated function; call `{type}.{name}(...)`")
	cRecvNotMutable      = defineCode("E515", "recv-not-mutable", "`{name}` takes `mut self` but `{place}` is immutable; {fix}")
	cRecvTemporary       = defineCode("E516", "recv-temporary", "`{name}` takes `mut self` but the receiver is a temporary")
	cMoveOutOfBorrow     = defineCode("E517", "move-out-of-borrow", "cannot move `{type}` out of a borrow")
	cPanicArgs           = defineCode("E518", "panic-args", "`panic` takes at most one argument, a `String` message")
	cPrintArg            = defineCode("E519", "print-arg", "`{name}` takes one `String` argument")
	cOptMemberNotOption  = defineCode("E520", "opt-member-not-option", "`?.` needs an `Option` operand, found `{type}`")
	cNotSupportedYet     = defineCode("E521", "not-supported-yet", "{what} is not supported yet")

	cOperatorUndefined      = defineCode("E600", "operator-undefined", "no operator `{op}` for ({types})")
	cOperatorSpacingHint    = defineCode("E601", "operator-spacing-hint", "`{op}` is not defined; if you meant `{a} {op1} {op2}{b}`, add a space")
	cOperatorAmbiguous      = defineCode("E602", "operator-ambiguous", "operator `{op}` for ({types}) is defined by both `{a}` and `{b}`")
	cOperatorHasSelf        = defineCode("E603", "operator-has-self", "operators are associated functions without `self`")
	cOperatorArity          = defineCode("E604", "operator-arity", "operator `{op}` takes {n} operand{s}")
	cOperatorForeignOperand = defineCode("E605", "operator-foreign-operands", "neither operand type of `{op}` is `{type}`")
	cOperatorPrimitive      = defineCode("E606", "operator-primitive", "operators on primitive types cannot be redefined")
	cOperatorReserved       = defineCode("E607", "operator-reserved", "`{op}` cannot be redefined")
	cUnaryMinusUnsigned     = defineCode("E608", "unary-minus-unsigned", "unary `-` on unsigned `{type}`")
	cShiftCountUsize        = defineCode("E609", "shift-count-usize", "shift count must be `usize`, found `{type}`")
	cEqUnsupported          = defineCode("E610", "eq-unsupported", "`==` is not defined for `{type}` (no `Eq`)")
	cOrdUnsupported         = defineCode("E611", "ord-unsupported", "`{op}` needs `Ord`; `{type}` has no `compareTo`")
	cCompoundResultType     = defineCode("E612", "compound-result-type", "`{op}` on (`{a}`, `{b}`) yields `{c}`, not `{a}`")
	cRangeOperands          = defineCode("E613", "range-operands", "range operands must be the same integer type")
	cNotIndexable           = defineCode("E614", "not-indexable", "`{type}` is not indexable")
	cIndexType              = defineCode("E615", "index-type", "index must be `usize` or `Range[usize]`, found `{type}`")
	cIndexCount             = defineCode("E616", "index-count", "indexing takes exactly one index")
	cIndexAssignUnsupported = defineCode("E617", "index-assign-unsupported", "index assignment is only supported for `Array[T]`")
	cPipeNotCall            = defineCode("E618", "pipe-not-call", "right-hand side of `|>` must be a call, a function name or a lambda; the left operand becomes the first argument")
	cFallbackNotSupported   = defineCode("E621", "fallback-not-supported", "`{type}` is not a Fallback (no `fn branch(move self) -> Branch[V, R]`)")
	cFallbackArmArity       = defineCode("E622", "fallback-arm-arity", "fallback handler takes exactly one parameter")
	cFallbackArmParamType   = defineCode("E623", "fallback-arm-param-type", "fallback handler parameter is `{R}`, annotated `{type}`")

	cUnusedResult          = defineCode("E700", "unused-result", "unused `{type}`; use `?`, `||`, or `_ =`")
	cAssignImmutable       = defineCode("E701", "assign-immutable", "`{name}` is immutable; {fix}")
	cAssignImmutableField  = defineCode("E702", "assign-immutable-field", "field `{name}` is immutable; {fix}")
	cAssignNotPlace        = defineCode("E703", "assign-not-place", "cannot assign to this expression")
	cReturnMissingValue    = defineCode("E704", "return-missing-value", "`return` needs a value of type `{type}`")
	cBreakOutsideLoop      = defineCode("E705", "break-outside-loop", "`{kw}` outside a loop")
	cForString             = defineCode("E706", "for-string", "`String` is not iterable; choose `s.bytes()`, `s.chars()` or `text.graphemes(s)`")
	cNotIterable           = defineCode("E707", "not-iterable", "`{type}` is not iterable")
	cAllocatorScopeType    = defineCode("E708", "allocator-scope-type", "`allocator` needs an `AllocatorScope`, found `{type}`")
	cFailOutsideResult     = defineCode("E709", "fail-outside-result", "`fail` requires a `Result` return type; this returns `{type}`")
	cTryOnOption           = defineCode("E710", "try-on-option", "`?` needs a `Result`; use `|| fail ...` for an `Option`")
	cTryNotResult          = defineCode("E711", "try-not-result", "`?` needs a `Result`, found `{type}`")
	cTryOutsideResult      = defineCode("E712", "try-outside-result", "`?` requires a `Result` return type; this returns `{type}`")
	cTryErrorMismatch      = defineCode("E713", "try-error-mismatch", "cannot propagate `{e}` from a function returning `Result[_, {e2}]`")
	cTryInLambdaUnknownRet = defineCode("E714", "try-in-lambda-unknown-return", "`?` in a lambda needs a known return type")
	cCleanupControlFlow    = defineCode("E715", "cleanup-control-flow", "{what} is not allowed in a cleanup body")
	cErrdeferOutsideResult = defineCode("E716", "errdefer-outside-result", "`errdefer` in a function that cannot fail")
	cForLoopScalarMut      = defineCode("E717", "for-loop-scalar-mut", "cannot bind a mutable `{type}` element in a `for` loop; index the collection instead")

	// break-with-value.
	cBreakValueLoopKind = defineCode("E1010", "break-value-loop-kind", "`break` with a value is only allowed in a value-less `for { }` loop")

	// named arguments.
	cPositionalAfterNamed = defineCode("E1011", "positional-after-named", "positional argument after a named argument")
	cNamedArgUnknown      = defineCode("E1012", "named-arg-unknown", "`{fn}` has no parameter named `{name}`")
	cNamedArgDuplicate    = defineCode("E1013", "named-arg-duplicate", "argument `{name}` given more than once")
	cNamedArgOnFnValue    = defineCode("E1014", "named-arg-fn-value", "a `fn` value has no parameter names; call it positionally")

	// Named lifetimes.
	cLifetimeReturnAnnot = defineCode("E1016", "lifetime-return-annotation", "a returned borrow needs a lifetime; annotate `&'a` here, or give the function exactly one `&'a` parameter to elide it")
	cLifetimeFieldAnnot  = defineCode("E1017", "lifetime-field-annotation", "a field cannot hold a borrow without a lifetime; add a lifetime parameter to this type, `['a]`, and write `&'a`")
	cLifetimeArgKind     = defineCode("E1018", "lifetime-arg-kind", "`{name}` expects {want} argument here, not {got}")
	cLifetimeUnresolved  = defineCode("E1019", "lifetime-unresolved", "undefined lifetime `{name}`")
	cLifetimeEscapes     = defineCode("E1020", "lifetime-escapes", "`{type}` carries a borrow and cannot be stored in {where}")

	// partial field move: a move out of a borrow reuses
	// cMoveOutOfBorrow (E517); index and Shared[T] get their own codes
	// (E1022/E1024).
	cMoveDropType   = defineCode("E1021", "move-drop-type", "cannot move `{name}` out of `{type}`, which defines a custom `drop`; add a `take`-style method that returns `{name}` instead")
	cMoveIndex      = defineCode("E1022", "move-index", "cannot move a value out of an index; clone the element instead")
	cMoveShared     = defineCode("E1024", "move-shared", "cannot move a value out of `{type}`; borrow its content instead")
	cMovePartialUse = defineCode("E1025", "move-partial-use", "`{name}` was moved out of `{owner}`; using the whole value needs it back")

	// A cleanup body must not suspend.
	cCleanupAwait = defineCode("E1026", "cleanup-await", "`await` is not allowed in a cleanup body")
)
