// Package llgen emits LLVM IR text from MIR.
package llgen

import (
	"fmt"
	"maps"
	"slices"
	"strings"

	"kigumi/internal/mir"
	"kigumi/internal/sem"
)

type emitter struct {
	p            *mir.Program
	entryAllocas []string
	hoisting     bool
	freestanding bool
	r            *sem.Result
	out          strings.Builder
	strs         map[string]string
	strList      []string
	descs        map[sem.EntityID]string
	vdescs       map[sem.EntityID]string
	tables       strings.Builder
	foreign      map[string]string
	helpers      strings.Builder
	cio          map[string]bool
	ntypes       int
	tmp          int
	stdDrops     map[sem.EntityID]bool
	shim         *cshim
	modAsm       strings.Builder
	symPrefix    string
	scalar       map[mir.LocalID]scalarInfo
}

func EmitProgram(p *mir.Program, opts EmitOptions) Output {
	e := &emitter{p: p, r: p.R, strs: map[string]string{}, descs: map[sem.EntityID]string{}, vdescs: map[sem.EntityID]string{}, foreign: map[string]string{}, stdDrops: map[sem.EntityID]bool{}, cio: map[string]bool{}, freestanding: opts.Freestanding, symPrefix: opts.SymbolPrefix, shim: newCshim()}
	var body strings.Builder
	for _, f := range p.Funcs {
		if e.r.Entity(f.Ent).Kind == sem.EntFn && e.r.Fn(f.Ent).Naked {
			e.nakedFn(f)
			continue
		}
		body.WriteString(e.function(f))
		body.WriteString(e.adapter(f))
		if e.r.Entity(f.Ent).Kind == sem.EntFn && e.r.Fn(f.Ent).Abi == "" {
			body.WriteString(e.bindAdapter(f))
		}
		if e.r.Entity(f.Ent).Kind == sem.EntFn && e.r.Fn(f.Ent).Recv != sem.RecvNone {
			body.WriteString(e.methodAdapter(f))
		}
		if e.r.Entity(f.Ent).Kind == sem.EntFn && e.r.Fn(f.Ent).Export != "" {
			if e.byValue(e.r.Fn(f.Ent).Sig) {
				body.WriteString(e.exportByval(f))
			} else {
				body.WriteString(e.exportWrapper(f))
			}
		}
	}
	// data() runs before declarations are written: std drop adapters it
	// builds may add foreign declarations of their own.
	data := e.data()
	e.out.WriteString(header)
	e.out.WriteString(e.modAsm.String())
	e.out.WriteString(externs)
	for _, name := range slices.Sorted(maps.Keys(e.foreign)) {
		e.out.WriteString(e.foreign[name] + "\n")
	}
	e.out.WriteString(data)
	e.out.WriteString(body.String())
	e.out.WriteString(e.helpers.String())
	e.out.WriteString(e.mainWrapper())
	return Output{IR: e.out.String(), CShim: e.shim.text()}
}

const header = `; generated by kigumi
%rt_type = type { ptr, i32, i32, ptr, i32, ptr, ptr, i64 }
%rt_variant = type { ptr, ptr, i32, i32 }

`

func (e *emitter) newTmp() string {
	e.tmp++
	return fmt.Sprintf("%%v%d", e.tmp)
}

func (e *emitter) function(f *mir.Func) string {
	var sb strings.Builder
	e.tmp = 0
	e.scalar = e.classifyScalars(f)
	fmt.Fprintf(&sb, "define ptr %s(", e.sym(f))
	for i := range f.Params {
		if i > 0 {
			sb.WriteString(", ")
		}
		fmt.Fprintf(&sb, "ptr %%p%d", i)
	}
	sb.WriteString(") {\nentry:\n")
	for i := range f.Locals {
		if info, ok := e.scalar[mir.LocalID(i)]; ok {
			fmt.Fprintf(&sb, "  %%l%d = alloca %s\n", i, info.Ty)
			fmt.Fprintf(&sb, "  store %s %s, ptr %%l%d\n", info.Ty, zeroOf(info.Ty), i)
			continue
		}
		fmt.Fprintf(&sb, "  %%l%d = alloca ptr\n", i)
		fmt.Fprintf(&sb, "  store ptr null, ptr %%l%d\n", i)
	}
	var body strings.Builder
	e.entryAllocas, e.hoisting = nil, true
	for bid, blk := range f.Blocks {
		fmt.Fprintf(&body, "b%d:\n", bid)
		for _, in := range blk.Insts {
			e.inst(&body, f, in)
		}
		e.term(&body, blk.Term)
	}
	e.hoisting = false
	for _, a := range e.entryAllocas {
		sb.WriteString(a)
	}
	// Parameters arrive owned or borrowed; either way, store as is.
	for i, prm := range f.Params {
		fmt.Fprintf(&sb, "  store ptr %%p%d, ptr %%l%d\n", i, prm)
	}
	sb.WriteString("  br label %b0\n")
	sb.WriteString(body.String())
	sb.WriteString("}\n\n")
	return sb.String()
}

func (e *emitter) load(sb *strings.Builder, l mir.LocalID) string {
	t := e.newTmp()
	fmt.Fprintf(sb, "  %s = load ptr, ptr %%l%d\n", t, l)
	return t
}

func (e *emitter) store(sb *strings.Builder, l mir.LocalID, v string) {
	fmt.Fprintf(sb, "  store ptr %s, ptr %%l%d\n", v, l)
}

func (e *emitter) term(sb *strings.Builder, t mir.Term) {
	switch t.Op {
	case mir.TermJump:
		fmt.Fprintf(sb, "  br label %%b%d\n", t.Targets[0])
	case mir.TermBranch:
		if info, ok := e.scalar[t.Args[0]]; ok && info.Ty == TI1 {
			c := e.loadNative(sb, t.Args[0])
			fmt.Fprintf(sb, "  br i1 %s, label %%b%d, label %%b%d\n", c.Text, t.Targets[0], t.Targets[1])
			return
		}
		v := e.load(sb, t.Args[0])
		c := e.irb(sb).Call(rtTruth, vptr(v)).Text
		fmt.Fprintf(sb, "  br i1 %s, label %%b%d, label %%b%d\n", c, t.Targets[0], t.Targets[1])
	case mir.TermReturn:
		if info, ok := e.scalar[t.Args[0]]; ok {
			boxed := e.boxNative(sb, info, e.loadNative(sb, t.Args[0]))
			fmt.Fprintf(sb, "  ret ptr %s\n", boxed)
			return
		}
		v := e.load(sb, t.Args[0])
		fmt.Fprintf(sb, "  ret ptr %s\n", v)
	default:
		sb.WriteString("  unreachable\n")
	}
}

func (e *emitter) mainWrapper() string {
	name := "main"
	if e.freestanding {
		name = "kigumi_main"
	}
	if e.p.Entry == nil {
		return "define i32 @" + name + "(i32 %argc, ptr %argv) {\n  ret i32 0\n}\n"
	}
	entry := e.sym(e.p.Entry)
	var sb strings.Builder
	fmt.Fprintf(&sb, "define i32 @%s(i32 %%argc, ptr %%argv) {\n", name)
	e.irb(&sb).Call(rtInit, vi32text("%argc"), vptr("%argv"), vi32(e.typeCount()), vptr("@rt_types"))
	fmt.Fprintf(&sb, "  %%r = call ptr %s()\n", entry)
	e.irb(&sb).CallAs("%c", rtExitCode, vptr("%r"))
	sb.WriteString("  ret i32 %c\n}\n")
	return sb.String()
}
